# Generated by Django 4.2.3 on 2023-09-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=100)),
                ('tea_type', models.CharField(choices=[('GREEN', 'Zielona'), ('WHITE', 'Biała'), ('BLACK', 'Czarna'), ('RED', 'Czerwona')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.tea')),
            ],
        ),
        migrations.CreateModel(
            name='TeaCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_amount', models.CharField(max_length=20)),
                ('water_temp', models.IntegerField()),
                ('steeping_time', models.IntegerField(verbose_name='Steeping time in minutes')),
                ('amount_of_steeps', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('tea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teas.tea')),
            ],
        ),
    ]
