# Generated by Django 4.2.3 on 2023-09-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacharacteristics',
            old_name='tea',
            new_name='tea_id',
        ),
        migrations.RenameField(
            model_name='teadescription',
            old_name='tea',
            new_name='tea_id',
        ),
    ]
