# Generated by Django 4.2.3 on 2023-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0002_rename_tea_teacharacteristics_tea_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teadescription',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
