# Generated by Django 4.2.3 on 2023-09-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0003_teadescription_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teadescription',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
