# Generated by Django 4.2.3 on 2023-09-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0004_alter_teadescription_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teadescription',
            old_name='tea_id',
            new_name='tea_ref',
        ),
    ]
