# Generated by Django 4.2.3 on 2023-09-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0005_rename_tea_id_teadescription_tea_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacharacteristics',
            old_name='tea_id',
            new_name='tea_ref',
        ),
    ]
