# Generated by Django 4.2.3 on 2023-09-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teas', '0007_alter_tea_tea_name_alter_tea_tea_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeaChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=15)),
                ('meeting_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('tea_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.tea')),
            ],
        ),
    ]
